# Site settings
title: Kleber Tertulino
description: "Tecnologia & Caf√©"
url: "https://klebertertulino.com"
paginate: 5
permalink: /:title

# Google Analytics
google_analytics: G-8Y13BPSXTP

# Author
author:
  name: Kleber Tertulino
  url: https://klebertertulino.com
  email: contato@klebertertulino.com

# Social
social-github: klebertertulino
social-linkedin: klebertertulino
social-email: contato@klebertertulino.com

# Build Settings
markdown: kramdown
include:
  - _pages
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
sass:
  sass_dir: _sass
  style: compressed

# Excludes
exclude: [Gemfile, Gemfile.lock, tale.gemspec]
